### ISSUE TITLE
服务器是不是挂了，出不来图片了

### ISSUE THREAD

**Issue by ElainaFanBoy** [6lszxz/nonebot-plugin-randomBugcatPic#1]
qaq

**Comment by 6lszxz** [comment]
俺这边用起来是没有问题的哦，服务器没问题的捏QAQ

**Comment by ElainaFanBoy** [comment]
无法访问此网站43.142.78.228 拒绝了我们的连接请求。
是不是被移动运营商给墙了qaq
但是之前用的好好的，最近就不行了

**Comment by 6lszxz** [comment]
嘶，不是很懂哎QAQ

**Comment by ElainaFanBoy** [comment]
> 嘶，不是很懂哎QAQ

可以要一份图片打包好的资源不，那我写个本地的呜呜
